### ISSUE TITLE
[FEATURE] 서버연결

### ISSUE THREAD

**Issue by Nahee-Park** [sopt/sopt.org-frontend#12]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 메인 이미지 불러오는 거 서버 연결
- 파트너스 서버 연결

## TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
