### ISSUE TITLE
history 페이지 개발 

### ISSUE THREAD

**Issue by Nahee-Park** [sopt/sopt.org-frontend#19]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 기수별 연혁 페이지 개발
- 역대 임원진 소개 페이지 개발

## TODO

- [ ] 기수별 연혁 페이지 개발
- [ ] 역대 임원진 소개 페이지 개발
