### ISSUE TITLE
[FEATURE] about 페이지 개발

### ISSUE THREAD

**Issue by Nahee-Park** [sopt/sopt.org-frontend#4]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x]  Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- about 페이지 개발

## TODO

- [ ] about 페이지 개발
- [ ] about 페이지 반응형 개발
