### ISSUE TITLE
[FEATURE] About Page 모바일 반응형

### ISSUE THREAD

**Issue by Nahee-Park** [sopt/sopt.org-frontend#9]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- about 페이지 모바일 반응형
- 디자인 디테일 수정

## TODO

- [ ] about 페이지 모바일 반응형
- [ ] 디자인 디테일 수정
